apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-valueuser
data:
  favoriteDrinkDefault: {{ .Values.favorite.drink | default "tea" | quote }}
  favoriteFood: {{ .Values.favorite.food | quote}}
  favoriteFoodUpper: {{ .Values.favorite.food | quote | upper }}
  favoriteFoodUpperRepeat: {{ .Values.favorite.food | repeat 5 | quote | upper }}
  conditionalFood: {{ .Values.favorite.food | upper | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true" 
  {{- end}}
  {{- with .Values.favorite }}
  scopeDrink: {{ .drink | default "tea" | quote }}
  scopeFood: {{ .food | upper | quote }}
  scopeReleaseName: {{ $.Release.Name}}
  {{- end}}