apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-valueuser
data:
  favoriteDrinkDefault: {{ .Values.favorite.drink | default "tea" | quote }}
  favoriteFood: {{ .Values.favorite.food | quote}}
  favoriteFoodUpper: {{ .Values.favorite.food | quote | upper }}
  favoriteFoodUpperRepeat: {{ .Values.favorite.food | repeat 5 | quote | upper }}
  conditionalFood: {{ .Values.favorite.food | upper | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true" 
  {{- end}}
  {{- $relname := .Release.Name -}}
  {{- with .Values.favorite }}
  scopeDrink: {{ .drink | default "tea" | quote }}
  scopeFood: {{ .food | upper | quote }}
  scopeReleaseName: {{ $.Release.Name}}
  varReleaseName: {{$relname}}
  {{- end}}
  toppings: |-
      {{- range .Values.pizzaToppings}}
      - {{ . | title | quote }}
      {{- end}}
  sizes: |-
    {{- range tuple "small" "medium" "large"}}
    - {{ . | title }}
    {{- end}}
  varToppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
      {{$index}}: {{$topping}}
    {{- end}}
  varKeyValues: |-
    {{- range $key, $val := .Values.favorite }}
      {{$key}}: {{$val}}
    {{- end}}